apiVersion: v1
kind: Service
metadata:
  name: fastapi-agent
spec:
  selector:
    app: fastapi-agent
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer   # Use NodePort if your cluster does not support LoadBalancer
